name: matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Log node version
        run: node -v

      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log node version
        run: node -v

    