name: GitHub actions

on: 
  push:
    branches: ["master"]

jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS actions
      - id: greet
      - uses: actions/hello-world-javascript-action@v1
      - with:
          who to greet: Mahabub
      - name: Log greet time
        run: echo "${{steps.greet.outputs.time}}"

          
